# Generated by Django 5.2.13 on 2026-05-28 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_invitation_id_alter_message_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.company')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='custom_role',
            field=models.ForeignKey(blank=True, help_text='Rol personalizado de la empresa. Si se asigna, sus permisos por módulo prevalecen sobre el rol base.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='accounts.role'),
        ),
    ]
