# Generated by Django 5.2.13 on 2026-05-29 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_role_membership_custom_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='accounts.role'),
        ),
    ]
