# Generated by Django 5.2.13 on 2026-06-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_invitation_custom_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('youtube', 'YouTube'), ('twitter', 'X (Twitter)'), ('tiktok', 'TikTok')], max_length=32),
        ),
    ]
