# Generated by Django 5.2.13 on 2026-06-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_socialaccount_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='stats_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
