# Generated by Django 5.2.13 on 2026-06-03 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_socialaccount_stats_socialaccount_stats_synced_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_post_id', models.CharField(max_length=256)),
                ('provider', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1024)),
                ('post_url', models.URLField(blank=True, max_length=1024)),
                ('post_type', models.CharField(default='video', max_length=32)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('duration_sec', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.socialaccount')),
            ],
            options={
                'ordering': ['-published_at'],
                'unique_together': {('account', 'platform_post_id')},
            },
        ),
    ]
