# Generated by Django 5.2.13 on 2026-06-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_socialpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(default='Espanya', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='plan',
            field=models.CharField(choices=[('free', 'Gratuït'), ('starter', 'Starter'), ('pro', 'Pro')], default='free', max_length=10),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Propietari'), ('admin', 'Administrador'), ('editor', 'Editor'), ('viewer', 'Només lectura')], default='editor', max_length=10),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendent'), ('accepted', 'Acceptada'), ('rejected', 'Rebutjada')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Propietari'), ('admin', 'Administrador'), ('editor', 'Editor'), ('viewer', 'Només lectura')], default='viewer', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('system', 'Sistema'), ('alert', 'Avís'), ('activity', 'Activitat')], default='system', max_length=10),
        ),
    ]
