# Generated by Django 5.2.13 on 2026-05-28 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_invitation_id_alter_message_id_and_more'),
        ('purchases', '0003_purchaseinvoice_odoo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='is_template',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='RecurringPurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('yearly', 'Anual')], default='monthly', max_length=12)),
                ('interval', models.PositiveIntegerField(default=1, help_text='Cada N periodos (p. ej. 2 = cada 2 meses).')),
                ('payment_term_days', models.PositiveIntegerField(default=30, help_text='Días entre emisión y vencimiento de cada factura generada.')),
                ('start_date', models.DateField()),
                ('next_run', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('max_occurrences', models.PositiveIntegerField(blank=True, null=True)),
                ('occurrences', models.PositiveIntegerField(default=0)),
                ('last_run', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_purchase_invoices', to='accounts.company')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurrence_plans', to='purchases.purchaseinvoice')),
            ],
            options={
                'ordering': ['-active', 'next_run'],
            },
        ),
    ]
