# Generated by Django 5.2.13 on 2026-06-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_restore_provider_fk_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_type',
            field=models.CharField(choices=[('Standard', 'Factura'), ('CreditNote', 'Nota de crèdit')], default='Standard', max_length=12),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='odoo_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='ID del account.move (in_invoice) associat a Odoo.', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='payment_method',
            field=models.CharField(default='Transferència 30 dies', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='status',
            field=models.CharField(choices=[('Draft', 'Esborrany'), ('Approved', 'Aprovada'), ('PartiallyPaid', 'Parcialment pagada'), ('Paid', 'Pagada'), ('Voided', 'Anul·lada'), ('Rectified', 'Rectificada')], default='Draft', max_length=15),
        ),
        migrations.AlterField(
            model_name='purchaseinvoicetimeline',
            name='event_type',
            field=models.CharField(choices=[('created', 'Creat'), ('updated', 'Actualitzat'), ('approved', 'Aprovat'), ('sent', 'Enviat'), ('payment', 'Pagament'), ('paid', 'Pagat'), ('voided', 'Anul·lat'), ('rectified', 'Rectificat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='method',
            field=models.CharField(choices=[('Transfer', 'Transferència'), ('DirectDebit', 'Domiciliació'), ('Card', 'Targeta'), ('Cash', 'Efectiu'), ('Other', 'Altre')], default='Transfer', max_length=15),
        ),
        migrations.AlterField(
            model_name='purchasequotedoc',
            name='status',
            field=models.CharField(choices=[('Draft', 'Esborrany'), ('Sent', 'Sol·licitat'), ('Accepted', 'Acceptat'), ('Rejected', 'Rebutjat'), ('Expired', 'Expirat'), ('Converted', 'Convertit')], default='Draft', max_length=15),
        ),
        migrations.AlterField(
            model_name='recurringpurchaseinvoice',
            name='interval',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recurringpurchaseinvoice',
            name='payment_term_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
