# Generated by Django 5.2.13 on 2026-04-13 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_saleschannel_company_tag_company_taxrate_company_and_more'),
        ('products', '0002_category_company_product_company_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReorderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_stock', models.IntegerField(help_text='Trigger reorder when stock falls to this level.')),
                ('reorder_qty', models.IntegerField(help_text='Quantity to reorder.')),
                ('max_stock', models.IntegerField(blank=True, help_text='Maximum desired stock level.', null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_rules', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_rules', to='core.warehouse')),
            ],
            options={
                'ordering': ['product__name'],
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
