# Generated by Django 5.2.13 on 2026-05-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_zero_existing_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prestashop_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='ID del product en PrestaShop (si está sincronizado).', null=True),
        ),
    ]
