# Generated by Django 5.2.13 on 2026-06-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_prestashop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Product', 'Producte'), ('Service', 'Servei')], default='Product', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Active', 'Actiu'), ('Inactive', 'Inactiu'), ('Archived', 'Arxivat')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('In', 'Entrada'), ('Out', 'Sortida'), ('Adjust', 'Ajust'), ('Return', 'Devolució')], max_length=10),
        ),
    ]
