# Generated by Django 5.2.13 on 2026-05-29 20:01

import django.db.models.deletion
import ecommerce_sync.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_invitation_custom_role'),
        ('core', '0002_saleschannel_company_tag_company_taxrate_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('prestashop', 'PrestaShop'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce')], default='prestashop', max_length=20)),
                ('base_url', models.URLField(default='http://localhost:8080', help_text='URL base de la tienda (sin /api).')),
                ('api_key', ecommerce_sync.fields.EncryptedTextField()),
                ('is_active', models.BooleanField(default=True)),
                ('push_products', models.BooleanField(default=True)),
                ('push_customers', models.BooleanField(default=True)),
                ('pull_orders', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('never', 'Nunca ejecutada')], default='never', max_length=10)),
                ('last_sync_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_connection', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_connections_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conexión e-commerce',
                'verbose_name_plural': 'Conexiones e-commerce',
            },
        ),
        migrations.CreateModel(
            name='EcommerceSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(help_text='Tipo de entidad ERP (ej: product, customer, order).', max_length=50)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('store_id', models.PositiveIntegerField(blank=True, null=True)),
                ('operation', models.CharField(choices=[('PUSH', 'Push (ERP → tienda)'), ('PULL', 'Pull (tienda → ERP)')], max_length=10)),
                ('method', models.CharField(help_text="Método HTTP/lógico (ej: 'GET', 'POST', 'PUT').", max_length=50)),
                ('success', models.BooleanField(default=False)),
                ('request_payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('response_excerpt', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_sync_logs', to='accounts.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de sincronización e-commerce',
                'verbose_name_plural': 'Logs de sincronización e-commerce',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'entity_type', '-created_at'], name='ecomlog_co_entity_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreTaxMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_tax_id', models.PositiveIntegerField(help_text='id del tax_rules_group en la tienda.')),
                ('store_tax_name', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_tax_mappings', to='accounts.company')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_mappings', to='core.taxrate')),
            ],
            options={
                'verbose_name': 'Mapeo de impuesto e-commerce',
                'verbose_name_plural': 'Mapeos de impuestos e-commerce',
                'constraints': [models.UniqueConstraint(fields=('company', 'tax_rate'), name='unique_store_tax_mapping_per_company')],
            },
        ),
    ]
