# Generated by Django 5.2.13 on 2026-05-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_odoo_id_email_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='prestashop_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='ID del customer en PrestaShop (si está sincronizado).', null=True),
        ),
    ]
