# Generated by Django 5.2.13 on 2026-04-17 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoiceseries_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='estado_aeat',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Enviado_Mock', 'Enviado (Mock)'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fecha_generacion_registro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='hash_actual',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='hash_anterior',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tipo_factura_verifactu',
            field=models.CharField(blank=True, default='', help_text='F1=Ordinaria, R1=Rectificativa (VeriFactu)', max_length=2),
        ),
        migrations.AddField(
            model_name='invoice',
            name='verifactu_csv',
            field=models.CharField(blank=True, help_text='CSV devuelto por la AEAT al aceptar el registro', max_length=100),
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=100)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('Alta', 'Alta de factura'), ('Intento_Modificacion', 'Intento de modificación'), ('Intento_Borrado', 'Intento de borrado'), ('Envio_AEAT', 'Envío a AEAT'), ('Aceptado_AEAT', 'Aceptado por AEAT'), ('Rechazado_AEAT', 'Rechazado por AEAT'), ('Generacion_PDF', 'Generación de PDF')], max_length=30)),
                ('detalles', models.TextField(blank=True)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='invoices.invoice')),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
