# Generated by Django 5.2.13 on 2026-04-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_company'),
        ('invoices', '0003_verifactu_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('series', 'number'), name='unique_invoice_number_per_series'),
        ),
    ]
