# Generated by Django 5.2.13 on 2026-05-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoice_is_template_recurringinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='prestashop_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='ID del order en PrestaShop que originó esta factura.', null=True),
        ),
    ]
