# Generated by Django 5.2.13 on 2026-05-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odooconnection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='odootaxmapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='entity_id',
            field=models.CharField(blank=True, default='', help_text='ID interno de la entidad (int o UUID en formato string).', max_length=64),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='entity_type',
            field=models.CharField(help_text='Tipo de entidad ERP (ej: customer, product, invoice).', max_length=50),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='odoo_method',
            field=models.CharField(help_text="Método Odoo invocado (ej: 'create', 'write', 'action_post').", max_length=50),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='request_payload_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 del payload enviado para diagnóstico.', max_length=64),
        ),
    ]
