# Generated by Django 5.2.13 on 2026-05-25 13:31

import accounting_sync.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_sync', '0002_alter_odooconnection_id_alter_odootaxmapping_id_and_more'),
        ('accounts', '0006_alter_invitation_id_alter_message_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdooProvisioningJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Procesando'), ('done', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=10)),
                ('database_name', models.CharField(max_length=100)),
                ('admin_password', accounting_sync.fields.EncryptedTextField(blank=True, default='')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('logs', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odoo_provisioning_jobs', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Job de aprovisionamiento Odoo',
                'verbose_name_plural': 'Jobs de aprovisionamiento Odoo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='accounting__status_349203_idx')],
            },
        ),
    ]
